from pong_logic import *
import time

PERIOD = 1/60.0
WINDOWWIDTH = 80
WINDOWHEIGHT = 20
WALLBOUND = (1, WINDOWWIDTH)
CEILINGBOUND = (1, WINDOWHEIGHT)
PADDLEDISTANCE = 2
PADDLEBOUND = (WALLBOUND[0] + PADDLEDISTANCE,
	WALLBOUND[1] - PADDLEDISTANCE)

PADDLESIZE = 3
LARGEPADDLESIZE = 6

clearScreen()

# Draw a net
my_net = Net((40, 0), BLUE, WINDOWHEIGHT)
my_net.draw()
time.sleep(5)